import { Box, Button, FormControl, Grid, InputLabel, MenuItem, Select, Stack, TextField, Typography } from '@mui/material'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'

export default function Home() {

  const [state, setState] = useState({
    q: "",
    limit: 100,
    page: 1
  })


  const handleChange = (e: any) => {
    const { value, name } = e.target
    setState({ ...state, [name]: value })
  }

  const router = useRouter()


  const handleSubmit = (e: any) => {
    e.preventDefault()
    const { q, page, limit, } = state;
    let qs = `?q=${q}&page=${page}&limit=${limit}`
    router.push(`/res${qs}`)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Image generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack sx={{ bgcolor: "gray", width: 600, p: 7, borderRadius: "4px", backdropFilter: "blur(4px)" }} spacing={2}>
          <Typography variant="h6" >Image generator{/*  */}</Typography>
          <Typography variant='caption' >Search products to generate images for</Typography>
          <Box>
            <Grid container spacing={2} >
              <Grid item xs >
                <FormControl fullWidth>
                  <InputLabel id="demo-simple-select-label">Page</InputLabel>
                  <Select
                    labelId="demo-simple-select-label"
                    id="demo-simple-select"
                    value={state.page}
                    label="Page"
                    name="page"
                    onChange={handleChange}
                  >
                    <MenuItem value={1}>1</MenuItem>
                    <MenuItem value={2}>2</MenuItem>
                    <MenuItem value={3}>3</MenuItem>
                    <MenuItem value={4}>4</MenuItem>

                    <MenuItem value={5}>5</MenuItem>
                    <MenuItem value={6}>6</MenuItem>

                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs >
                <FormControl fullWidth>
                  <InputLabel id="demo-simple-select-label">Limit</InputLabel>
                  <Select
                    labelId="demo-simple-select-label"
                    id="demo-simple-select"
                    value={state.limit}
                    label="Limit"
                    onChange={handleChange}
                  >
                    <MenuItem value={100}>100</MenuItem>
                    <MenuItem value={300}>300</MenuItem>
                    <MenuItem value={600}>600</MenuItem>
                  </Select>
                </FormControl>
              </Grid>

            </Grid>
          </Box>
          <form onSubmit={handleSubmit}>
            <TextField name="q" required fullWidth color="secondary" onChange={handleChange} type="search" InputProps={{ endAdornment: <Button type='submit' color="secondary" variant={"contained"} disableElevation >Submit</Button> }} label="Search product" />
          </form>
        </Stack>
      </main>
    </div>
  )
}